orbs:
  docker: circleci/docker@1.6.0
  tester: talkiq/tester@3.0.1

  # Added tester

version: 2.1
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: qainsights/circleci-test:latest
    steps:
    - checkout
    - setup_remote_docker
    - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
    - run: docker run -p 5000:5000 -d qainsights/circleci-test:latest

workflows:
  example-workflow:
    jobs:
      - example-job 


